{% set name = "llmtuner" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hiyouga/LLaMA-Factory/archive/v{{ version }}.tar.gz
  sha256: 420f6d923cd13472055220d7bcb19f9bdad922b56798f0757ad364323e216565

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - pyyaml
    - packaging
    - python >=3.8
    - pytorch >=1.13.1
    - transformers >=4.37.2
    - datasets >=2.14.3
    - accelerate <=0.33.0,>=0.30.1
    - peft >=0.10.0
    - trl <=0.9.6,>=0.8.6
    - gradio >=4.0.0
    - scipy
    - einops
    - sentencepiece
    - protobuf
    - uvicorn
    - pydantic
    - fastapi
    - sse-starlette
    - matplotlib-base >=3.7.0
    - fire
    - galore-torch
    - tiktoken

test:
  imports:
    - llamafactory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hiyouga/LLaMA-Factory
  summary: Easy-to-use LLM fine-tuning framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
